services:
  - type: web
    name: sms-spam-detector
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
